spring.application.name=sistema-academico

# Conexión a MySQL80 en el puerto 3307
spring.datasource.url=jdbc:mysql://localhost:3307/sistema_academico?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=UnionLatina2004

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Ruta para la interfaz de Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html 